baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Packet Analysis"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  # Combined with current relative page, shows source page on Github
  editURL = "https://github.com/pocc/tshark.dev/blob/hugo-learn/content/"
  description = "Packet Analysis, Scripted"
  author = "Ross Jacobs"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  themeVariant = "blue"
  disableInlineCopyToClipBoard = "true"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Tshark Guide"
weight = 1
languageName = "English"

PygmentsCodeFences = true
PygmentsStyle = "monokai"
