baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Tshark Guide"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://swit.sh"
  description = "Packet Analysis, Scripted"
  author = "Ross Jacobs"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/pocc/tshark.dev"
weight = 0

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "https://github.com/pocc/tshark.dev/contributors"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "　"
weight = 15

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-servicestack'></i> Wireshark Links"
url = "https://wireshark.org"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-servicestack'></i> Wireshark Links"
url = "https://wireshark.org"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "　<i class='fas fa-question-circle'></i> Ask Wireshark"
url = "https://ask.wireshark.org"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "　<i class='fas fa-fw fa-atlas'></i> Developer's Guide"
url = "https://www.wireshark.org/docs/wsdg_html_chunked/"
weight = 50

[[Languages.en.menu.shortcuts]]
name = "　<i class='fas fa-fw fa-book'></i> Man Pages"
url = "https://www.wireshark.org/docs/man-pages/"
weight = 60

[[Languages.en.menu.shortcuts]]
name = "　<i class='fas fa-fw fa-bug'></i> Bugzilla"
url = "https://www.wireshark.org/docs/man-pages/"
weight = 70
