[build]
publish = "public"
command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.65.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.65.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.65.3"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.65.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/webfonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Required for expected behavior
[[redirects]]	
  from = "/home"	
  to = "/"	
  status = 301
  force = true
